Repository kuruklg/repo-tpFinal, pull requests merged in 2023-07, with the labels that each got.

#14 Se crea la entidad Receta
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/entity/Receta.java
Labels: Funcionalidad

#16 Implementacion de la capa service para la entidad Receta
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/repository/IRecetaRepository.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/RecetaServiceImp.java
Labels: enhancement

#20 controllers de paginas
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/CalcularIMCController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/ContactoController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/GestionController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/IndexController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/PesoIdealController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/RecetaController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/TestimonioController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/entity/Receta.java
  tpFinal_Grupo16/src/main/resources/static/index-images/icono.png
  tpFinal_Grupo16/src/main/resources/templates/contacto.html
  tpFinal_Grupo16/src/main/resources/templates/gestion.html
  tpFinal_Grupo16/src/main/resources/templates/index.html
  tpFinal_Grupo16/src/main/resources/templates/layouts/footer.html
  tpFinal_Grupo16/src/main/resources/templates/layouts/header.html
  tpFinal_Grupo16/src/main/resources/templates/recetas.html
  tpFinal_Grupo16/src/main/resources/templates/servicio-calcularimc.html
  tpFinal_Grupo16/src/main/resources/templates/servicio-pesoideal.html
  tpFinal_Grupo16/src/main/resources/templates/testimonios.html
Labels: JAVA develop, Thymeleaf develop

#21 Recetas e ingredientes
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/GestionController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/GestionRecetaController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/entity/Ingrediente.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/entity/Receta.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/repository/IRecetaRepository.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/IRecetaService.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/imp/RecetaServiceImp.java
  tpFinal_Grupo16/src/main/resources/application.properties
  tpFinal_Grupo16/src/main/resources/templates/gestion-recetas.html
  tpFinal_Grupo16/src/main/resources/templates/layouts/header.html
  tpFinal_Grupo16/src/main/resources/templates/nueva-receta.html
Labels: Thymeleaf develop

#24 Recetas e ingredientes
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/GestionRecetaController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/RecetaController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/entity/Ingrediente.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/entity/Receta.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/repository/IIngredienteRepository.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/IIngredienteService.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/IRecetaService.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/imp/IngredienteServiceImp.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/imp/RecetaServiceImp.java
  tpFinal_Grupo16/src/main/resources/static/css/estilos.css
  tpFinal_Grupo16/src/main/resources/templates/gestion-recetas.html
  tpFinal_Grupo16/src/main/resources/templates/ingredientes.html
  tpFinal_Grupo16/src/main/resources/templates/nueva-receta.html
  tpFinal_Grupo16/src/main/resources/templates/nuevo-ingrediente.html
  tpFinal_Grupo16/src/main/resources/templates/receta-por-categoria.html
  tpFinal_Grupo16/src/main/resources/templates/recetas.html
Labels: HTML design, Thymeleaf develop

#25 imagenes de las categorias de recetas
  tpFinal_Grupo16/src/main/resources/static/recetas-images/bebidas.jpg
  tpFinal_Grupo16/src/main/resources/static/recetas-images/carnes.jpg
  tpFinal_Grupo16/src/main/resources/static/recetas-images/dulces.jpg
  tpFinal_Grupo16/src/main/resources/static/recetas-images/ensaladas.jpg
  tpFinal_Grupo16/src/main/resources/static/recetas-images/legumbresycereales.jpg
  tpFinal_Grupo16/src/main/resources/static/recetas-images/pan.jpg
  tpFinal_Grupo16/src/main/resources/static/recetas-images/pescado.jpg
  tpFinal_Grupo16/src/main/resources/static/recetas-images/sopasycremas.jpg
Labels: enhancement

#26 Creación de registro
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/UsuarioController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/entity/Usuario.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/repository/IUsuarioRepository.java
  tpFinal_Grupo16/src/main/resources/templates/registro.html
Labels: Documentation, Funcionalidad, HTML design, JAVA develop

#29 Corrección y Gesion de Usuarios
  tpFinal_Grupo16/bin/src/main/resources/templates/layouts/header.html
  tpFinal_Grupo16/bin/src/main/resources/templates/registro.html
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/GestionUsuarioController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/UsuarioController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/entity/Usuario.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/IUsuarioService.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/imp/UsuarioServiceImp.java
  tpFinal_Grupo16/src/main/resources/templates/gestion-usuarios.html
Labels: bug fixes, Documentation, HTML design, JAVA develop, Thymeleaf develop

#31 Actualizacion de pagina contactos
  tpFinal_Grupo16/src/main/resources/static/css/estilos.css
  tpFinal_Grupo16/src/main/resources/templates/contacto.html
Labels: CSS design

#32 Actualizacion del inicio
  tpFinal_Grupo16/src/main/resources/static/contacto-images/banner_contactanos_vital.jpg
  tpFinal_Grupo16/src/main/resources/static/css/estilos.css
  tpFinal_Grupo16/src/main/resources/static/index-images/banner-alimentacion.jpeg
  tpFinal_Grupo16/src/main/resources/static/index-images/banner-calculo-imc.jpeg
  tpFinal_Grupo16/src/main/resources/static/index-images/banner-peso-ideal.jpeg
  tpFinal_Grupo16/src/main/resources/templates/index.html
Labels: HTML design, CSS design

#39 Estilo a formulario de registro
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/entity/Usuario.java
  tpFinal_Grupo16/src/main/resources/static/css/estilos.css
  tpFinal_Grupo16/src/main/resources/static/index-images/calculo-imc.jpg
  tpFinal_Grupo16/src/main/resources/static/index-images/peso-ideal.jpg
  tpFinal_Grupo16/src/main/resources/templates/registro.html
Labels: CSS design

#40 Actualizacion de header
  tpFinal_Grupo16/src/main/resources/templates/layouts/header.html
Labels: CSS design

#41 Actualizacion de listas en footer
  tpFinal_Grupo16/src/main/resources/templates/layouts/footer.html
Labels: CSS design

#42 correcciones en viewport height de dos paginas
  tpFinal_Grupo16/src/main/resources/application.properties
  tpFinal_Grupo16/src/main/resources/static/css/estilos.css
  tpFinal_Grupo16/src/main/resources/templates/gestion-testimonios.html
  tpFinal_Grupo16/src/main/resources/templates/layouts/header.html
  tpFinal_Grupo16/src/main/resources/templates/testimonios.html
Labels: bug fixes, CSS design

#54 Servicio imc3
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/CalcularIMCController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/UsuarioController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/entity/IndiceMasaCorporal.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/entity/Usuario.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/repository/IIndiceIMCRepository.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/IIndiceIMCService.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/IRecetaService.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/IUsuarioService.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/imp/IndiceIMCImp.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/imp/UsuarioServiceImp.java
  tpFinal_Grupo16/src/main/resources/application.properties
  tpFinal_Grupo16/src/main/resources/templates/registro.html
  tpFinal_Grupo16/src/main/resources/templates/servicio-calcularimc.html
Labels: Funcionalidad

#55 se crea login antes de consultar el imc del usuario
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/controller/CalcularIMCController.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/entity/IndiceMasaCorporal.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/IIndiceIMCService.java
  tpFinal_Grupo16/src/main/java/ar/edu/unju/fi/service/imp/IndiceIMCImp.java
  tpFinal_Grupo16/src/main/resources/static/css/estilos.css
  tpFinal_Grupo16/src/main/resources/templates/layouts/header.html
  tpFinal_Grupo16/src/main/resources/templates/registro.html
  tpFinal_Grupo16/src/main/resources/templates/servicio-calcularimc.html
Labels: Funcionalidad

#63 62. Se mejora la tabla de gestion de testimonios
  tpFinal_Grupo16/src/main/resources/templates/gestion-testimonios.html
Labels: CSS design
